### ISSUE TITLE
Dotfile symlink torie

### ISSUE THREAD

**Issue by V1RE** [jascha030/config-nvim#1]
Ja ik kon het niet laten, maar handmatig symlinks regelen kan ik echt niet aanzien.

[GNUrobi Stow](https://alexpearce.me/2016/02/managing-dotfiles-with-stow/)

**Comment by jascha030** [comment]
Ja maar nee, het punt van de README is dat je het lekker zelf mag uitzoeken.

(https://github.com/jascha030/.dotfiles)

**Comment by V1RE** [comment]
Ik sluit bij deze de issue aangezien ik er vanuit mag gaan dat je dit even in de google docs zet 🤡
